### ISSUE TITLE
Issues with Quality Controlled Data Files

### ISSUE THREAD

**Issue by horsburgh** [UCHIC/iUtahUtilities#10]
@AmberSJones and @fryarludwig - here’s some things I found as I looked through the quality controlled data files. These probably need some effort from both of you to resolve:
- [x] The spatial reference system for the latitude and longitude coordinates of the Site is missing. I think you may have already fixed this.
- [x] Something weird is going on with the MethodLink. The MethodLink in the pH file is missing the “m” at the end of “.com” and the one for DO just says “Non” – which I assume means “None” but missing the last character.  This also seems inconsistent that one Quality Controlled Dataset retains method information from the sensor used to measure it and one talks about ODM Tools Python.  I think we need a more consistent Method Description for quality controlled data (Kenny – the first part may be a bug, but the more complete Method description would be a database issue that Amber would need to fix).
- [x] I think the NoData value should just be -9999 and not -9999.0 (unless it has to include the zero)
- [x] The Citation is problematic as it is inconsistent with what will be listed on the landing page in HydroShare. We should either not list the citation inside the file, or we need to modify it to be consistent with the HydroShare one. I suspect the former option would be easiest.
- [x] Is there a reason to show the Qualifier IDs in the Qualifier Information block?  They aren’t actually used in the file. Also, the spacing on the “Description” header is off by one character.
- [x] Each file needs a statement that these data have been subject to quality control procedures. This could go either in the Header at the top where the warning is or in a separate section below the qualifiers block called “Quality Control Level Information”.

**Comment by fryarludwig** [comment]
Spatial reference - fixed in issue #3. 
MethodLink - Guaranteed to print 'None' when empty, and now prints the entire link
NoDataValue - No longer printed with decimal point when the NDV is a whole number
Citation list is now removed
Qualitifers - ID column removed, dropped a space between 'Code' and 'Description'
**QC Procedure Statement** - @AmberSJones, can you provide a statement for me to use? I think we should add it to the header block.

**Comment by fryarludwig** [comment]
Also, should mention: I mirrored the following changes for the Raw Data file headers as well: LatLonDataum (SpatialReference), MethodLink, and NoData value.

**Comment by AmberSJones** [comment]
@fryarludwig - sounds like you've addressed a lot of this.
- Regarding the disparities in Method Descriptions, I probably need to chat with the technicians about how to be more consistent in the Methods used for QC1 data.
- Removing the citation is definitely the easiest option at this point.
- Statement regarding Quality Control: How about "These data have passed QA/QC procedures such as sensor calibration and visual inspection and removal of obvious errors. These data are approved by Technicians as the best available version of the data. See published script for correction steps specific to this data series."
