### ISSUE TITLE
Organization as Author

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUtahUtilities#16]
We need to use an organization as an author in the automatically generated metadata for the QC1 resources. We need 'iUTAH GAMUT Working Group' to be listed as the first author and to be selected as an organization rather than an individual. This can be done through the web entry, @fryarludwig will investigate implementing it for the API.

**Comment by fryarludwig** [comment]
This has been done for QC1 resources only. Raw Data resources will need to be recreated or will need this to be performed manually.
