### ISSUE TITLE
Missing lat/lon datum information

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUtahUtilities#3]
In the header of the GAMUT files, the Lat/Lon datum is missing from the Site block.

**Comment by AmberSJones** [comment]
This still needs to be added to the raw GAMUT files as well as the QC files under development.

**Comment by fryarludwig** [comment]
I can see the Lat/Long lines on all the files the script generates on my local machine, and the raw files I checked on HydroShare also have these lines. Can you point me to an example file that doesn't have these?

**Comment by AmberSJones** [comment]
So, I think all of the files have Latitude and Longitude, but not the LatLonDatum.

**Comment by fryarludwig** [comment]
Added "# LatLonDatum: {srs_name}" to the header, populates correctly in all my tests.
