### ISSUE TITLE
Files for QC1 Data on HydroShare

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUtahUtilities#8]
@fryarludwig recently put forward an example file for the QC1 data series files being written to HydroShare. There are several tweaks to the files that need to be made:
- [x] Add CensorCode to the columns being displayed
- [x] Display the QualifierCode instead of the QualifierID
- [x] Make the column order: LocalDateTime, UTCOffset, UTCDateTime, [Variable], CensorCode, QualifierCode
- [x] Add a block to the header to display information on any Qualifiers contained in the file. The header should show QualifierCode and QualifierDescription (see the example file that I emailed to you)
- [x] Change the disclaimer at the top to read "WARNING: The data are released on the condition that neither iUTAH nor any of its participants may be held liable for any damages resulting from their use. The following metadata describe the data in this file:"

**Comment by fryarludwig** [comment]
In progress

**Comment by fryarludwig** [comment]
These have been completed - I've emailed you some revised files to review

**Comment by AmberSJones** [comment]
I think this looks great. Closing.
